[workspace]
members = [
    "halo2",
    "halo2_gadgets",
    "halo2_proofs",
    "halo2_curves",
    "ff",
    "group"
]

[patch.crates-io]
ff = { path = "ff" }
group = { path = "group" }

[patch."https://github.com/privacy-scaling-explorations/halo2curves.git"]
halo2curves = { path = "halo2_curves" }

[profile.bench]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = true
incremental = false
codegen-units = 1
